version: '3.5'
services:

  api:
    image: rtakauti/pismo_go
    container_name: 'api'
    environment:
      DB_NAME: 'pismo'
      DB_USER: 'root'
      DB_PASSWORD: 123
    ports:
      - '80:80'
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: rtakauti/pismo_mysql
    container_name: 'mysql'
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123

networks:
  default:
    external:
      name: webproxy